# Configuração para o GitHub Pages
title: "Developer Handbook"
description: "Documentação e práticas recomendadas para desenvolvedores da qbem."
url: "https://qbem-repos.github.io"
baseurl: "/developer-handbook"

# Tema do Jekyll
theme: minima

# Caminho do logotipo
logo: "/assets/images/logo.webp"

# Outras configurações recomendadas para GitHub Pages
plugins:
  - jekyll-feed
