# Configuração para GitHub Pages
title: "Qbem Developer Handbook"
description: "Documentação e práticas recomendadas para desenvolvedores da Qbem."
url: "https://qbem-repos.github.io"
baseurl: "/developer-handbook"

# Tema remoto
remote_theme: "daattali/beautiful-jekyll"

# Caminho do logotipo
logo: "/assets/images/logo.webp"

# Plugins compatíveis com GitHub Pages
plugins:
  - jekyll-feed

# Configurações adicionais para o tema Beautiful Jekyll
author: Tecn
show_excerpts: true
show_footer_links: false
footer_copyright: "© 2024 Qbem"
social_networks:
  - name: github
    url: "https://github.com/qbem-repos"

# Configuração de Markdown e Realce de Código
markdown: kramdown
highlighter: rouge

# Configuração de permalinks para URLs amigáveis
permalink: pretty
