# Configuração para o GitHub Pages
title: "Developer Handbook"
description: "Documentação e práticas recomendadas para desenvolvedores."
url: "https://github.com/qbem-repos"
baseurl: "/developer-handbook"

# Tema do Jekyll
theme: "hacker"

# Caminho do logotipo
logo: "/assets/images/logo.webp"
